using System.Linq;
using Content.Shared._DV.Traits;
using Content.Shared._WF.OutlawObjectives;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._WF.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class OutlawObjectivesTab : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public event Action<ProtoId<TraitPrototype>, bool>? OnObjectiveToggled;

    private readonly Dictionary<ProtoId<TraitPrototype>, CheckBox> _toggles = new();

    public OutlawObjectivesTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        IntroLabel.SetMessage(Loc.GetString("outlaw-objectives-intro"), defaultColor: Color.White);
        NoteLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("outlaw-objectives-note")), defaultColor: Color.Yellow);

        var objectives = _prototype.EnumeratePrototypes<OutlawObjectivePrototype>()
            .OrderBy(objective => objective.ID);

        foreach (var objective in objectives)
        {
            var trait = objective.Trait;
            var toggle = new CheckBox { Text = Loc.GetString(_prototype.Index(trait).Name) };
            toggle.OnToggled += args => OnObjectiveToggled?.Invoke(trait, args.Pressed);

            _toggles[trait] = toggle;
            ObjectiveList.AddChild(toggle);
        }
    }

    public void SetSelected(IReadOnlySet<ProtoId<TraitPrototype>> traits)
    {
        foreach (var (trait, toggle) in _toggles)
            toggle.Pressed = traits.Contains(trait);
    }
}
