using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class NavRadarSettingsWindow : FancyWindow
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public NavRadarSettingsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        // Setup IFF Grouping dropdown
        IFFGroupingDropdown.AddItem("None", 0);
        IFFGroupingDropdown.AddItem("Lax", 1);
        IFFGroupingDropdown.AddItem("Aggressive", 2);

        // Setup Label Font Size dropdown
        LabelFontSizeDropdown.AddItem("6", 0);
        LabelFontSizeDropdown.AddItem("8", 1);
        LabelFontSizeDropdown.AddItem("10", 2);

        // Wire up dropdown handlers to maintain selection state
        IFFGroupingDropdown.OnItemSelected += args => IFFGroupingDropdown.SelectId(args.Id);
        LabelFontSizeDropdown.OnItemSelected += args => LabelFontSizeDropdown.SelectId(args.Id);

        // Load current values
        LoadCurrentSettings();

        // Wire up buttons
        SettingsApplyButton.OnPressed += _ => ApplySettings();
        SettingsCloseButton.OnPressed += _ => Close();
    }

    private void LoadCurrentSettings()
    {
        // Load IFF Grouping
        var grouping = _cfg.GetCVar(CCVars.ShuttleIFFGrouping);
        IFFGroupingDropdown.SelectId(grouping);

        // Load Label Font Size
        var fontSize = _cfg.GetCVar(CCVars.ShuttleLabelFontSize);
        var fontSizeIndex = fontSize switch
        {
            6 => 0,
            8 => 1,
            10 => 2,
            _ => 1 // Default to 8
        };
        LabelFontSizeDropdown.SelectId(fontSizeIndex);
        
        // Load Hide Edge Labels
        HideEdgeLabelsCheckBox.Pressed = _cfg.GetCVar(CCVars.ShuttleHideEdgeLabels);

        // Wayfarer: Load Ignore Edge Inactive Shuttles
        IgnoreEdgeInactiveShuttlesCheckBox.Pressed = _cfg.GetCVar(CCVars.ShuttleIgnoreEdgeInactiveShuttles);
    }

    private void ApplySettings()
    {
        // Save IFF Grouping
        var grouping = IFFGroupingDropdown.SelectedId;
        _cfg.SetCVar(CCVars.ShuttleIFFGrouping, grouping);

        // Save Label Font Size
        var fontSizeIndex = LabelFontSizeDropdown.SelectedId;
        var fontSize = fontSizeIndex switch
        {
            0 => 6,
            1 => 8,
            2 => 10,
            _ => 8
        };
        _cfg.SetCVar(CCVars.ShuttleLabelFontSize, fontSize);
        
        // Save Hide Edge Labels
        _cfg.SetCVar(CCVars.ShuttleHideEdgeLabels, HideEdgeLabelsCheckBox.Pressed);

        // Wayfarer: Save Ignore Edge Inactive Shuttles
        _cfg.SetCVar(CCVars.ShuttleIgnoreEdgeInactiveShuttles, IgnoreEdgeInactiveShuttlesCheckBox.Pressed);

        Close();
    }
}
