- type: latheRecipePack
  id: WFServiceBoards
  recipes:
      - JuicerIndustrialMachineCircuitboard

- type: latheRecipePack
  id: WFServiceStatic
  recipes:
      - ServicePitcher
      - DrinkMugBlack
      - DrinkMugBlue
      - DrinkMugGreen
      - DrinkMugHeart
      - DrinkMugMoebius
      - DrinkMugOne
      - DrinkMugRainbow
      - DrinkMugRed
