- type: entity
  id: PortableGeneratorBioPacmanMachineCircuitboard
  parent: PortableGeneratorPacmanMachineCircuitboard
  name: B.I.O.P.A.C.M.A.N. portable generator machine board # Frontier: no -type
  components:
  - type: MachineBoard
    prototype: PortableGeneratorBioPacman

- type: entity
  id: WFOutlawTechFabCircuitboard
  parent: BaseMachineCircuitboard
  name: outlaw techfab machine board
  description: A machine printed circuit board for an outlaw techfab.
  components:
  - type: Sprite
    sprite: _NF/Objects/Misc/module.rsi
    state: pirate
  - type: MachineBoard
    prototype: WFOutlawTechfab
    requirements:
      MatterBin: 2
      Manipulator: 2
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker
