using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CommunityGoals;
using Content.Shared._WF.CommunityGoals.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;
using Robust.Shared.Maths;

namespace Content.Client._WF.CommunityGoals.UI;

[GenerateTypedNameReferences]
public sealed partial class CommunityGoalConsoleWindow : FancyWindow
{
    public Action? OnContribute;

    public CommunityGoalConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        ContributeButton.OnPressed += _ => OnContribute?.Invoke();
    }

    public void UpdateState(CommunityGoalConsoleState state)
    {
        // Update slot display
        if (state.SlottedItemPrototype != null)
        {
            SlotLabel.Text = state.SlottedItemName != null
                ? $"{state.SlottedItemName}  ×{state.SlottedItemAmount}"
                : $"{state.SlottedItemPrototype}  ×{state.SlottedItemAmount}";
            SlotLabel.FontColorOverride = Color.White;
            ContributeButton.Disabled = false;
        }
        else
        {
            SlotLabel.Text = "— empty —";
            SlotLabel.FontColorOverride = Color.FromHex("#888888");
            ContributeButton.Disabled = true;
        }

        // Rebuild goals list
        GoalsList.RemoveAllChildren();

        if (state.ActiveGoals.Count == 0)
        {
            GoalsList.AddChild(new Label
            {
                Text = "No community goals are active this round.",
                FontColorOverride = Color.FromHex("#888888"),
                Margin = new Thickness(4),
            });
            return;
        }

        foreach (var goal in state.ActiveGoals)
        {
            GoalsList.AddChild(BuildGoalEntry(goal, state.SlottedItemPrototype));
            GoalsList.AddChild(new PanelContainer
            {
                StyleClasses = { "LowDivider" },
                Margin = new Thickness(0, 4, 0, 4),
            });
        }
    }

    private static Control BuildGoalEntry(CommunityGoalData goal, string? slottedProto)
    {
        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(4, 2),
        };

        // Title
        root.AddChild(new Label
        {
            Text = goal.Title,
            FontColorOverride = Color.FromHex("#aaffaa"),
        });

        // Description
        root.AddChild(new Label
        {
            Text = goal.Description,
            Margin = new Thickness(8, 0, 0, 4),
            FontColorOverride = Color.FromHex("#cccccc"),
        });

        // Requirements
        foreach (var req in goal.Requirements)
        {
            root.AddChild(BuildRequirementBar(req, slottedProto));
        }

        if (goal.Requirements.Count == 0)
        {
            root.AddChild(new Label
            {
                Text = "  (no requirements defined)",
                FontColorOverride = Color.FromHex("#666666"),
            });
        }

        return root;
    }

    private static Control BuildRequirementBar(CommunityGoalRequirementData req, string? slottedProto)
    {
        var isCompleted = req.CurrentAmount >= req.RequiredAmount;
        var isSlotMatch = slottedProto != null &&
                          slottedProto.Equals(req.EntityPrototypeId, StringComparison.OrdinalIgnoreCase);

        var pct = req.RequiredAmount > 0
            ? Math.Clamp((double)req.CurrentAmount / req.RequiredAmount, 0, 1)
            : 1.0;

        var name = req.DisplayName ?? req.EntityPrototypeId;
        var progress = $"{req.CurrentAmount:N0} / {req.RequiredAmount:N0}";

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(12, 1),
        };

        // Label row
        var labelRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        var bullet = isSlotMatch ? "▶ " : "• ";
        labelRow.AddChild(new Label
        {
            Text = $"{bullet}{name}",
            HorizontalExpand = true,
            FontColorOverride = isCompleted
                ? Color.FromHex("#aaffaa")
                : isSlotMatch
                    ? Color.FromHex("#ffffaa")
                    : Color.White,
        });
        labelRow.AddChild(new Label
        {
            Text = isCompleted ? $"{progress}  ✓" : progress,
            FontColorOverride = isCompleted ? Color.FromHex("#aaffaa") : Color.FromHex("#aaaaaa"),
        });
        row.AddChild(labelRow);

        // Progress bar (simple coloured panel)
        var barBg = new PanelContainer
        {
            MinSize = new Vector2(0, 8),
            HorizontalExpand = true,
            Margin = new Thickness(0, 2, 0, 4),
        };
        barBg.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#333333") };

        var barFill = new PanelContainer
        {
            HorizontalAlignment = HAlignment.Left,
            MinSize = new Vector2(0, 8),
        };
        barFill.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = isCompleted ? Color.FromHex("#44aa44") : Color.FromHex("#4488cc"),
        };

        // We'll use a custom layout approach: wrap in a ratio container via code
        var bar = new ProgressBar
        {
            Value = (float)pct,
            MinSize = new Vector2(0, 12),
            HorizontalExpand = true,
        };
        row.AddChild(bar);

        return row;
    }
}
