using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CommunityGoals;
using Content.Shared._WF.CommunityGoals.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._WF.CommunityGoals.UI;

[GenerateTypedNameReferences]
public sealed partial class CommunityGoalConsoleWindow : FancyWindow
{
    public Action? OnCommit;
    public Action? OnClearStaging;
    public Action<int>? OnContributeToRequirement;

    public CommunityGoalConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        HintLabel.SetMessage(
            "Use items on this terminal or donation pallet to stage them for contribution.",
            defaultColor: Color.FromHex("#555555"));

        CommitButton.OnPressed += _ => OnCommit?.Invoke();
        ClearButton.OnPressed += _ => OnClearStaging?.Invoke();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        // Only allow moving the window by dragging the title bar (above the contents area).
        if (relativeMousePos.Y < ContentsContainer.Position.Y)
            return DragMode.Move;
        return DragMode.None;
    }

    public void UpdateState(CommunityGoalConsoleState state)
    {
        // Staging area
        StagingList.RemoveAllChildren();

        var totalStacks = state.StagedItems.Count;
        var hasPalletItems = state.PalletItems.Count > 0;
        var hasItems = totalStacks > 0 || hasPalletItems;

        StagingCount.Text = hasItems
            ? $"{totalStacks} type{(totalStacks != 1 ? "s" : "")} staged{(hasPalletItems ? $", {state.PalletItems.Count} on pallet" : "")}"
            : "nothing staged";
        StagingCount.FontColorOverride = hasItems ? Color.White : Color.FromHex("#888888");
        CommitButton.Disabled = !hasItems;
        ClearButton.Disabled = totalStacks == 0;
        HintLabel.Visible = !hasItems;

        foreach (var item in state.StagedItems)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(4, 1) };

            // Highlight if this type matches any active goal requirement
            var matched = state.ActiveGoals
                .Any(g => g.Requirements.Any(r =>
                    (!r.IsKillOrder && r.EntityPrototypeId != null && r.EntityPrototypeId.Equals(item.PrototypeId, StringComparison.OrdinalIgnoreCase))
                    || (r.TagId != null && item.PrototypeId == $"tag:{r.TagId}")));

            row.AddChild(new Label
            {
                Text = $"• {item.DisplayName}",
                HorizontalExpand = true,
                FontColorOverride = matched ? Color.FromHex("#ffffaa") : Color.FromHex("#cccccc"),
                ToolTip = item.PrototypeId,
            });
            row.AddChild(new Label
            {
                Text = $"×{item.Amount:N0}",
                FontColorOverride = matched ? Color.FromHex("#ffffaa") : Color.FromHex("#888888"),
                Margin = new Thickness(8, 0, 0, 0),
            });

            if (!matched)
            {
                row.AddChild(new Label
                {
                    Text = "  (not needed)",
                    FontColorOverride = Color.FromHex("#cc6666"),
                });
            }

            StagingList.AddChild(row);
        }

        //  Pallet items 
        if (hasPalletItems)
        {
            StagingList.AddChild(new Label
            {
                Text = "── on donation pallet ──",
                FontColorOverride = Color.FromHex("#7799aa"),
                Margin = new Thickness(4, 4, 4, 1),
            });

            foreach (var item in state.PalletItems)
            {
                var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(4, 1) };

                var matched = state.ActiveGoals
                    .Any(g => g.Requirements.Any(r =>
                        (!r.IsKillOrder && r.EntityPrototypeId != null && r.EntityPrototypeId.Equals(item.PrototypeId, StringComparison.OrdinalIgnoreCase))
                        || (r.TagId != null && item.PrototypeId == $"tag:{r.TagId}")));

                row.AddChild(new Label
                {
                    Text = $"• {item.DisplayName}",
                    HorizontalExpand = true,
                    FontColorOverride = matched ? Color.FromHex("#aaddff") : Color.FromHex("#888888"),
                    ToolTip = item.PrototypeId,
                });
                row.AddChild(new Label
                {
                    Text = $"×{item.Amount:N0}",
                    FontColorOverride = matched ? Color.FromHex("#aaddff") : Color.FromHex("#666666"),
                    Margin = new Thickness(8, 0, 0, 0),
                });

                StagingList.AddChild(row);
            }
        }

        // Goals list
        GoalsList.RemoveAllChildren();

        if (state.ActiveGoals.Count == 0)
        {
            GoalsList.AddChild(new Label
            {
                Text = "No community goals are active this round.",
                FontColorOverride = Color.FromHex("#888888"),
                Margin = new Thickness(4),
            });
            return;
        }

        // Use the server-computed requirement keys for isStaged checks (covers both proto and tag matching)
        var reqKeys = state.StagedRequirementKeys;

        foreach (var goal in state.ActiveGoals)
        {
            GoalsList.AddChild(BuildGoalEntry(goal, reqKeys, OnContributeToRequirement));
            GoalsList.AddChild(new PanelContainer
            {
                StyleClasses = { "LowDivider" },
                Margin = new Thickness(0, 4, 0, 4),
            });
        }
    }

    private static Control BuildGoalEntry(CommunityGoalData goal, List<string> reqKeys, Action<int>? onContribute)
    {
        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(4, 2),
        };

        root.AddChild(new Label
        {
            Text = goal.Title,
            FontColorOverride = Color.FromHex("#aaffaa"),
        });

        root.AddChild(new RichTextLabel
        {
            Text = goal.Description,
            HorizontalExpand = true,
            MaxWidth = 440f,
            Margin = new Thickness(8, 0, 0, 4),
        });

        foreach (var req in goal.Requirements)
        {
            root.AddChild(BuildRequirementBar(req, reqKeys, onContribute));
        }

        if (goal.Requirements.Count == 0)
        {
            root.AddChild(new Label
            {
                Text = "  (no requirements defined)",
                FontColorOverride = Color.FromHex("#666666"),
            });
        }

        return root;
    }

    private static Control BuildRequirementBar(CommunityGoalRequirementData req, List<string> reqKeys, Action<int>? onContribute)
    {
        var isCompleted = req.CurrentAmount >= req.RequiredAmount;
        var isStaged = !req.IsKillOrder && (req.TagId != null
            ? reqKeys.Contains($"tag:{req.TagId}")
            : req.EntityPrototypeId != null && reqKeys.Contains(req.EntityPrototypeId));

        var pct = req.RequiredAmount > 0
            ? Math.Clamp((double)req.CurrentAmount / req.RequiredAmount, 0, 1)
            : 1.0;

        var name = req.DisplayName ?? req.TagId ?? req.EntityPrototypeId;
        var progress = $"{req.CurrentAmount:N0} / {req.RequiredAmount:N0}";

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(12, 1),
        };

        // Label row
        var labelRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        var bullet = req.IsKillOrder ? "☠ " : isStaged && !isCompleted ? "▶ " : "• ";
        labelRow.AddChild(new Label
        {
            Text = $"{bullet}{name}",
            HorizontalExpand = true,
            FontColorOverride = isCompleted
                ? Color.FromHex("#aaffaa")
                : isStaged
                    ? Color.FromHex("#ffffaa")
                    : Color.White,
        });
        labelRow.AddChild(new Label
        {
            Text = isCompleted ? $"{progress}  ✓" : progress,
            FontColorOverride = isCompleted ? Color.FromHex("#aaffaa") : Color.FromHex("#aaaaaa"),
            Margin = new Thickness(8, 0, 0, 0),
        });

        // Kill-order requirements are satisfied by killing the target, not by delivering items —
        // no per-requirement contribute button for those.
        if (!req.IsKillOrder)
        {
            var reqId = req.Id;
            var contributeBtn = new Button
            {
                Text = Loc.GetString("community-goal-console-contribute-req"),
                Disabled = isCompleted || !isStaged,
                Margin = new Thickness(8, 0, 0, 0),
            };
            contributeBtn.OnPressed += _ => onContribute?.Invoke(reqId);
            labelRow.AddChild(contributeBtn);
        }

        row.AddChild(labelRow);

        var bar = new ProgressBar
        {
            MinValue = 0,
            MaxValue = 1,
            Value = (float)pct,
            MinHeight = 12,
            HorizontalExpand = true,
        };
        row.AddChild(bar);

        return row;
    }
}
