using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CommunityGoals;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using EntityPrototype = Robust.Shared.Prototypes.EntityPrototype;

namespace Content.Client._WF.CommunityGoals.UI;

[GenerateTypedNameReferences]
public sealed partial class CommunityGoalsWindow : FancyWindow
{
    private readonly IPrototypeManager _protoManager;

    // Callbacks → EUI
    public Action<string, string, int?, int?>? OnCreateGoal;
    public Action<int, string, string, int?, int?, bool>? OnUpdateGoal;
    public Action<int>? OnDeleteGoal;
    public Action<int, string, string?, long>? OnAddRequirement;
    public Action<int>? OnRemoveRequirement;

    public CommunityGoalsWindow()
    {
        _protoManager = IoCManager.Resolve<IPrototypeManager>();
        RobustXamlLoader.Load(this);

        CreateGoalButton.OnPressed += _ =>
        {
            var title = NewTitle.Text.Trim();
            var desc = NewDescription.Text.Trim();
            if (string.IsNullOrWhiteSpace(title))
                return;

            int? startRound = int.TryParse(NewStartRound.Text.Trim(), out var s) ? s : null;
            int? endRound = int.TryParse(NewEndRound.Text.Trim(), out var e) ? e : null;

            OnCreateGoal?.Invoke(title, desc, startRound, endRound);

            NewTitle.Text = string.Empty;
            NewDescription.Text = string.Empty;
            NewStartRound.Text = string.Empty;
            NewEndRound.Text = string.Empty;
        };
    }

    public void HandleState(CommunityGoalsEuiState state)
    {
        GoalsList.RemoveAllChildren();

        foreach (var goal in state.Goals)
        {
            GoalsList.AddChild(BuildGoalPanel(goal));
            GoalsList.AddChild(new PanelContainer { StyleClasses = { "LowDivider" }, Margin = new Thickness(0, 4, 0, 4) });
        }

        if (state.Goals.Count == 0)
        {
            GoalsList.AddChild(new Label { Text = "No community goals defined yet.", Margin = new Thickness(6) });
        }
    }

    private Control BuildGoalPanel(CommunityGoalData goal)
    {
        var root = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(4, 2) };

        // ── Header row: [Active] Title [Edit] [Delete]
        var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        var activeCheck = new CheckBox { Text = string.Empty, Pressed = goal.IsActive, ToolTip = "Active" };
        header.AddChild(activeCheck);

        var titleLabel = new Label
        {
            Text = goal.Title,
            HorizontalExpand = true,
            FontColorOverride = goal.IsActive ? Color.FromHex("#aaffaa") : Color.FromHex("#888888"),
            Margin = new Thickness(4, 0),
        };
        header.AddChild(titleLabel);

        var roundInfo = new Label
        {
            Text = $"Rounds: {goal.StartRound?.ToString() ?? "any"} → {goal.EndRound?.ToString() ?? "∞"}",
            Margin = new Thickness(8, 0),
            FontColorOverride = Color.FromHex("#aaaaaa"),
        };
        header.AddChild(roundInfo);

        var editButton = new Button { Text = "Edit", MinWidth = 50 };
        var deleteButton = new Button { Text = "Delete", MinWidth = 60, Modulate = Color.FromHex("#ff8888") };
        header.AddChild(editButton);
        header.AddChild(deleteButton);
        root.AddChild(header);

        // Description
        root.AddChild(new Label { Text = goal.Description, Margin = new Thickness(20, 0, 0, 2), FontColorOverride = Color.FromHex("#cccccc") });

        // Requirements section
        var reqHeader = new Label { Text = "Requirements:", Margin = new Thickness(20, 2, 0, 0), FontColorOverride = Color.FromHex("#ddddaa") };
        root.AddChild(reqHeader);

        foreach (var req in goal.Requirements)
        {
            root.AddChild(BuildRequirementRow(req));
        }

        // Add requirement row
        root.AddChild(BuildAddRequirementRow(goal.Id));

        // ── Edit form (hidden by default, toggled by Edit button)
        var editForm = BuildEditForm(goal);
        editForm.Visible = false;
        root.AddChild(editForm);

        editButton.OnPressed += _ => { editForm.Visible = !editForm.Visible; };
        deleteButton.OnPressed += _ => { OnDeleteGoal?.Invoke(goal.Id); };

        // Active toggle applies immediately
        activeCheck.OnToggled += args =>
        {
            OnUpdateGoal?.Invoke(goal.Id, goal.Title, goal.Description, goal.StartRound, goal.EndRound, args.Pressed);
        };

        return root;
    }

    private Control BuildRequirementRow(CommunityGoalRequirementData req)
    {
        var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(28, 1) };

        // Icon preview
        if (_protoManager.TryIndex<EntityPrototype>(req.EntityPrototypeId, out _))
        {
            var icon = new EntityPrototypeView { MinWidth = 20, MinHeight = 20, Margin = new Thickness(0, 0, 4, 0), VerticalAlignment = VAlignment.Center };
            icon.SetPrototype(req.EntityPrototypeId);
            row.AddChild(icon);
        }

        var name = req.DisplayName ?? req.EntityPrototypeId;
        var progress = $"{req.CurrentAmount:N0} / {req.RequiredAmount:N0}";
        var pct = req.RequiredAmount > 0 ? (double)req.CurrentAmount / req.RequiredAmount * 100 : 0;
        var done = req.CurrentAmount >= req.RequiredAmount;

        var label = new Label
        {
            Text = $"• {name}   {progress}   ({pct:F0}%)",
            HorizontalExpand = true,
            FontColorOverride = done ? Color.FromHex("#aaffaa") : Color.White,
            ToolTip = req.EntityPrototypeId,
        };
        row.AddChild(label);

        var removeBtn = new Button { Text = "Remove", MinWidth = 65, Modulate = Color.FromHex("#ff9966") };
        removeBtn.OnPressed += _ => { OnRemoveRequirement?.Invoke(req.Id); };
        row.AddChild(removeBtn);

        return row;
    }

    private Control BuildAddRequirementRow(int goalId)
    {
        var outer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(28, 2) };

        // ── Row 1: prototype ID + live validation
        var searchRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 2) };

        var protoIcon = new EntityPrototypeView
        {
            MinWidth = 24, MinHeight = 24,
            Margin = new Thickness(0, 0, 4, 0),
            VerticalAlignment = VAlignment.Center,
            Visible = false,
        };
        var protoField = new LineEdit { PlaceHolder = "Prototype ID (e.g. SheetPlasteel)", HorizontalExpand = true, MinWidth = 180 };
        var statusLabel = new Label
        {
            Text = string.Empty,
            Margin = new Thickness(6, 0),
            VerticalAlignment = VAlignment.Center,
            FontColorOverride = Color.FromHex("#888888"),
        };

        searchRow.AddChild(new Label { Text = "Proto: ", VerticalAlignment = VAlignment.Center });
        searchRow.AddChild(protoIcon);
        searchRow.AddChild(protoField);
        searchRow.AddChild(statusLabel);
        outer.AddChild(searchRow);

        // ── Row 2: display name + amount + add button
        var addRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        var nameField = new LineEdit { PlaceHolder = "Display name (auto-filled)", MinWidth = 150 };
        var amountField = new LineEdit { PlaceHolder = "Required amount", MinWidth = 100 };
        var addBtn = new Button { Text = "Add Requirement", MinWidth = 110 };

        addRow.AddChild(new Label { Text = "Name: ", VerticalAlignment = VAlignment.Center });
        addRow.AddChild(nameField);
        addRow.AddChild(new Label { Text = " Qty: ", Margin = new Thickness(6, 0), VerticalAlignment = VAlignment.Center });
        addRow.AddChild(amountField);
        addRow.AddChild(addBtn);
        outer.AddChild(addRow);

        // Live prototype validation: on each keystroke look up the proto
        protoField.OnTextChanged += args =>
        {
            var id = args.Text.Trim();
            if (string.IsNullOrWhiteSpace(id))
            {
                protoIcon.Visible = false;
                statusLabel.Text = string.Empty;
                return;
            }

            if (_protoManager.TryIndex<EntityPrototype>(id, out var proto))
            {
                protoIcon.SetPrototype(id);
                protoIcon.Visible = true;
                statusLabel.Text = $"✓ {proto.Name}";
                statusLabel.FontColorOverride = Color.FromHex("#aaffaa");

                // Auto-fill display name if it hasn't been manually set
                if (string.IsNullOrWhiteSpace(nameField.Text))
                    nameField.Text = proto.Name;
            }
            else
            {
                protoIcon.Visible = false;
                statusLabel.Text = "✗ Not found";
                statusLabel.FontColorOverride = Color.FromHex("#ff8888");
            }
        };

        addBtn.OnPressed += _ =>
        {
            var protoId = protoField.Text.Trim();
            if (string.IsNullOrWhiteSpace(protoId))
                return;
            if (!_protoManager.HasIndex<EntityPrototype>(protoId))
                return; // block adding unknown prototypes
            if (!long.TryParse(amountField.Text.Trim(), out var amount) || amount <= 0)
                return;

            var displayName = string.IsNullOrWhiteSpace(nameField.Text) ? null : nameField.Text.Trim();
            OnAddRequirement?.Invoke(goalId, protoId, displayName, amount);

            // Clear fields
            protoField.Text = string.Empty;
            nameField.Text = string.Empty;
            amountField.Text = string.Empty;
            protoIcon.Visible = false;
            statusLabel.Text = string.Empty;
        };

        return outer;
    }

    private Control BuildEditForm(CommunityGoalData goal)
    {
        var form = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(20, 2) };

        form.AddChild(new Label { Text = "── Edit Goal ──", FontColorOverride = Color.FromHex("#ffdd88") });

        var titleRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2) };
        titleRow.AddChild(new Label { Text = "Title:", MinWidth = 60 });
        var titleEdit = new LineEdit { Text = goal.Title, HorizontalExpand = true };
        titleRow.AddChild(titleEdit);
        form.AddChild(titleRow);

        var descRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2) };
        descRow.AddChild(new Label { Text = "Desc:", MinWidth = 60 });
        var descEdit = new LineEdit { Text = goal.Description, HorizontalExpand = true };
        descRow.AddChild(descEdit);
        form.AddChild(descRow);

        var roundRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2) };
        roundRow.AddChild(new Label { Text = "Start:", MinWidth = 45 });
        var startEdit = new LineEdit { Text = goal.StartRound?.ToString() ?? string.Empty, MinWidth = 80, PlaceHolder = "(any)" };
        roundRow.AddChild(startEdit);
        roundRow.AddChild(new Label { Text = " End:", Margin = new Thickness(8, 0, 4, 0) });
        var endEdit = new LineEdit { Text = goal.EndRound?.ToString() ?? string.Empty, MinWidth = 80, PlaceHolder = "(never)" };
        roundRow.AddChild(endEdit);
        form.AddChild(roundRow);

        var saveBtn = new Button { Text = "Save Changes", Margin = new Thickness(0, 4) };
        saveBtn.OnPressed += _ =>
        {
            var title = titleEdit.Text.Trim();
            var desc = descEdit.Text.Trim();
            if (string.IsNullOrWhiteSpace(title))
                return;

            int? startRound = int.TryParse(startEdit.Text.Trim(), out var s) ? s : null;
            int? endRound = int.TryParse(endEdit.Text.Trim(), out var e) ? e : null;

            OnUpdateGoal?.Invoke(goal.Id, title, desc, startRound, endRound, goal.IsActive);
        };
        form.AddChild(saveBtn);

        return form;
    }
}
