using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CommunityGoals;
using Content.Shared.Stacks;
using Content.Shared.Tag;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using EntityPrototype = Robust.Shared.Prototypes.EntityPrototype;

namespace Content.Client._WF.CommunityGoals.UI;

[GenerateTypedNameReferences]
public sealed partial class CommunityGoalsWindow : FancyWindow
{
    private readonly IPrototypeManager _protoManager;

    // Callbacks → EUI
    public Action<string, string, int?, int?>? OnCreateGoal;
    public Action<int, string, string, int?, int?, bool>? OnUpdateGoal;
    public Action<int>? OnDeleteGoal;
    public Action<int, string?, string?, bool, string?, long>? OnAddRequirement;
    public Action<int>? OnRemoveRequirement;    public Action<int, long>? OnUpdateRequirement;
    public CommunityGoalsWindow()
    {
        _protoManager = IoCManager.Resolve<IPrototypeManager>();
        RobustXamlLoader.Load(this);

        // Tab titles are set initially; HandleState updates them with counts.
        GoalTabs.SetTabTitle(0, "Active");
        GoalTabs.SetTabTitle(1, "Upcoming");
        GoalTabs.SetTabTitle(2, "Expired");

        CreateGoalButton.OnPressed += _ =>
        {
            var title = NewTitle.Text.Trim();
            var desc = NewDescription.Text.Trim();
            if (string.IsNullOrWhiteSpace(title))
                return;

            int? startRound = int.TryParse(NewStartRound.Text.Trim(), out var s) ? s : null;
            int? endRound = int.TryParse(NewEndRound.Text.Trim(), out var e) ? e : null;

            OnCreateGoal?.Invoke(title, desc, startRound, endRound);

            NewTitle.Text = string.Empty;
            NewDescription.Text = string.Empty;
            NewStartRound.Text = string.Empty;
            NewEndRound.Text = string.Empty;
        };
    }

    public void HandleState(CommunityGoalsEuiState state)
    {
        ActiveGoalsList.RemoveAllChildren();
        UpcomingGoalsList.RemoveAllChildren();
        ExpiredGoalsList.RemoveAllChildren();

        var expired  = state.Goals.Where(g => g.EndRound != null && g.EndRound < state.CurrentRound).ToList();
        var active   = state.Goals.Where(g => g.IsActive && (g.EndRound == null || g.EndRound >= state.CurrentRound)).ToList();
        var upcoming = state.Goals.Where(g => !g.IsActive && (g.EndRound == null || g.EndRound >= state.CurrentRound)).ToList();

        GoalTabs.SetTabTitle(0, $"Active ({active.Count})");
        GoalTabs.SetTabTitle(1, $"Upcoming ({upcoming.Count})");
        GoalTabs.SetTabTitle(2, $"Expired ({expired.Count})");

        PopulateGoalList(ActiveGoalsList,   active,   "No active community goals.");
        PopulateGoalList(UpcomingGoalsList, upcoming, "No upcoming community goals.");
        PopulateGoalList(ExpiredGoalsList,  expired,  "No expired community goals.");

        // Force a fresh layout pass so RichTextLabel word-wrap and ScrollContainer
        // heights are calculated against the actual window size, not the infinite
        // size used during OpenCentered's initial Measure call.
        InvalidateMeasure();
    }

    private void PopulateGoalList(BoxContainer list, List<CommunityGoalData> goals, string emptyText)
    {
        foreach (var goal in goals)
        {
            list.AddChild(BuildGoalPanel(goal));
            list.AddChild(new PanelContainer { StyleClasses = { "LowDivider" }, Margin = new Thickness(0, 4, 0, 4) });
        }

        if (goals.Count == 0)
        {
            list.AddChild(new Label { Text = emptyText, Margin = new Thickness(6), FontColorOverride = Color.FromHex("#666666") });
        }
    }

    private Control BuildGoalPanel(CommunityGoalData goal)
    {
        var root = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(4, 2) };

        // Header row: [Active] Title [Edit] [Delete]
        var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        var activeCheck = new CheckBox { Text = string.Empty, Pressed = goal.IsActive, ToolTip = "Active" };
        header.AddChild(activeCheck);

        var titleLabel = new Label
        {
            Text = goal.Title,
            HorizontalExpand = true,
            FontColorOverride = goal.IsActive ? Color.FromHex("#aaffaa") : Color.FromHex("#888888"),
            Margin = new Thickness(4, 0),
        };
        header.AddChild(titleLabel);

        var roundInfo = new Label
        {
            Text = $"Rounds: {goal.StartRound?.ToString() ?? "any"} → {goal.EndRound?.ToString() ?? "∞"}",
            Margin = new Thickness(8, 0),
            FontColorOverride = Color.FromHex("#aaaaaa"),
        };
        header.AddChild(roundInfo);

        var editButton = new Button { Text = "Edit", MinWidth = 50 };
        var deleteButton = new Button { Text = "Delete", MinWidth = 60, Modulate = Color.FromHex("#ff8888") };
        header.AddChild(editButton);
        header.AddChild(deleteButton);
        root.AddChild(header);

        // Description
        var descLabel = new RichTextLabel { HorizontalExpand = true, Margin = new Thickness(20, 0, 0, 2) };
        descLabel.SetMessage(goal.Description, defaultColor: Color.FromHex("#cccccc"));
        root.AddChild(descLabel);

        // Requirements section
        var reqHeader = new Label { Text = "Requirements:", Margin = new Thickness(20, 2, 0, 0), FontColorOverride = Color.FromHex("#ddddaa") };
        root.AddChild(reqHeader);

        foreach (var req in goal.Requirements)
        {
            root.AddChild(BuildRequirementRow(req));
        }

        // Add requirement row
        root.AddChild(BuildAddRequirementRow(goal.Id));

        // Edit form (hidden by default, toggled by Edit button)
        var editForm = BuildEditForm(goal);
        editForm.Visible = false;
        root.AddChild(editForm);

        editButton.OnPressed += _ => { editForm.Visible = !editForm.Visible; };
        deleteButton.OnPressed += _ => ShowDeleteConfirmation(goal);

        // Active toggle applies immediately
        activeCheck.OnToggled += args =>
        {
            OnUpdateGoal?.Invoke(goal.Id, goal.Title, goal.Description, goal.StartRound, goal.EndRound, args.Pressed);
        };

        return root;
    }

    /// <summary>
    /// Pops up a confirmation window before deleting a goal — this permanently removes the goal,
    /// all of its requirements, and its contribution history, and cannot be undone.
    /// </summary>
    private void ShowDeleteConfirmation(CommunityGoalData goal)
    {
        var window = new DefaultWindow
        {
            Title = "Delete Community Goal",
            MinSize = new Vector2(300, 140),
        };

        var content = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(8) };

        var warningLabel = new RichTextLabel { MaxWidth = 280f, Margin = new Thickness(0, 0, 0, 8) };
        var safeTitle = goal.Title.Replace("[", "(").Replace("]", ")");
        warningLabel.SetMessage(FormattedMessage.FromMarkupPermissive(
            $"Are you sure you want to delete \"{safeTitle}\"?\n\n" +
            "This will permanently remove the goal, all of its requirements, and all recorded contributions. " +
            "[color=#ff8888]This is a destructive action and cannot be undone.[/color]"),
            defaultColor: Color.White);
        content.AddChild(warningLabel);

        var buttonRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalAlignment = HAlignment.Right };
        var cancelBtn = new Button { Text = "Cancel", MinWidth = 80 };
        var confirmBtn = new Button
        {
            Text = "Delete Permanently",
            MinWidth = 130,
            Margin = new Thickness(6, 0, 0, 0),
            StyleClasses = { StyleNano.StyleClassButtonColorRed },
        };
        buttonRow.AddChild(cancelBtn);
        buttonRow.AddChild(confirmBtn);
        content.AddChild(buttonRow);

        window.Contents.AddChild(content);

        cancelBtn.OnPressed += _ => window.Close();
        confirmBtn.OnPressed += _ =>
        {
            OnDeleteGoal?.Invoke(goal.Id);
            window.Close();
        };

        window.OpenCentered();
    }

    private Control BuildRequirementRow(CommunityGoalRequirementData req)
    {
        var outer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(28, 1) };

        // Main row
        var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        // Icon preview — prototype-based only
        if (req.IsKillOrder)
        {
            var killBadge = new Label
            {
                Text = "[kill]",
                FontColorOverride = Color.FromHex("#ff9966"),
                Margin = new Thickness(0, 0, 4, 0),
                VerticalAlignment = VAlignment.Center,
            };
            row.AddChild(killBadge);

            if (req.EntityPrototypeId != null && _protoManager.TryIndex<EntityPrototype>(req.EntityPrototypeId, out _))
            {
                var killIcon = new EntityPrototypeView { MinWidth = 20, MinHeight = 20, Margin = new Thickness(0, 0, 4, 0), VerticalAlignment = VAlignment.Center };
                killIcon.SetPrototype(req.EntityPrototypeId);
                row.AddChild(killIcon);
            }
        }
        else if (req.EntityPrototypeId != null && _protoManager.TryIndex<EntityPrototype>(req.EntityPrototypeId, out _))
        {
            var icon = new EntityPrototypeView { MinWidth = 20, MinHeight = 20, Margin = new Thickness(0, 0, 4, 0), VerticalAlignment = VAlignment.Center };
            icon.SetPrototype(req.EntityPrototypeId);
            row.AddChild(icon);
        }
        else if (req.TagId != null)
        {
            var tagBadge = new Label
            {
                Text = $"[tag]",
                FontColorOverride = Color.FromHex("#88ccff"),
                Margin = new Thickness(0, 0, 4, 0),
                VerticalAlignment = VAlignment.Center,
            };
            row.AddChild(tagBadge);
        }

        var name = req.DisplayName ?? req.TagId ?? req.EntityPrototypeId ?? "?";
        var tooltip = req.IsKillOrder ? $"kill:{req.EntityPrototypeId}" : req.TagId != null ? $"tag:{req.TagId}" : (req.EntityPrototypeId ?? "");
        var progress = $"{req.CurrentAmount:N0} / {req.RequiredAmount:N0}";
        var pct = req.RequiredAmount > 0 ? (double)req.CurrentAmount / req.RequiredAmount * 100 : 0;
        var done = req.CurrentAmount >= req.RequiredAmount;

        var label = new Label
        {
            Text = $"• {name}   {progress}   ({pct:F0}%)",
            HorizontalExpand = true,
            FontColorOverride = done ? Color.FromHex("#aaffaa") : Color.White,
            ToolTip = tooltip,
        };
        row.AddChild(label);

        var editBtn = new Button { Text = "Edit", MinWidth = 50, Margin = new Thickness(4, 0, 0, 0) };
        var removeBtn = new Button { Text = "Remove", MinWidth = 65, Modulate = Color.FromHex("#ff9966"), Margin = new Thickness(4, 0, 0, 0) };
        row.AddChild(editBtn);
        row.AddChild(removeBtn);
        outer.AddChild(row);

        // Inline edit row (hidden by default)
        var editRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2, 0, 2), Visible = false };
        editRow.AddChild(new Label { Text = "New qty:", Margin = new Thickness(24, 0, 4, 0), VerticalAlignment = VAlignment.Center });
        var qtyField = new LineEdit { Text = req.RequiredAmount.ToString(), MinWidth = 100, PlaceHolder = "20" };
        editRow.AddChild(qtyField);
        var saveBtn = new Button { Text = "Save", MinWidth = 50, Margin = new Thickness(6, 0, 0, 0) };
        editRow.AddChild(saveBtn);
        var cancelBtn = new Button { Text = "Cancel", MinWidth = 60, Margin = new Thickness(4, 0, 0, 0) };
        editRow.AddChild(cancelBtn);
        outer.AddChild(editRow);

        editBtn.OnPressed += _ => { editRow.Visible = !editRow.Visible; };
        cancelBtn.OnPressed += _ => { editRow.Visible = false; qtyField.Text = req.RequiredAmount.ToString(); };
        saveBtn.OnPressed += _ =>
        {
            if (!long.TryParse(qtyField.Text.Trim(), out var qty) || qty <= 0)
                return;
            OnUpdateRequirement?.Invoke(req.Id, qty);
            editRow.Visible = false;
        };

        removeBtn.OnPressed += _ => { OnRemoveRequirement?.Invoke(req.Id); };

        return outer;
    }

    private Control BuildAddRequirementRow(int goalId)
    {
        var outer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(28, 2) };

        // ── Mode toggle: Prototype vs Tag vs Kill Order
        var modeRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 2) };
        var useTagCheck = new CheckBox { Text = "Tag mode", ToolTip = "Check to add a tag-based requirement (e.g. 'Trash') instead of a specific prototype." };
        var useKillCheck = new CheckBox { Text = "Kill order", Margin = new Thickness(8, 0, 0, 0), ToolTip = "Check to add a kill-order requirement (e.g. 'NFMobCarp') satisfied by killing that mob instead of delivering it." };
        modeRow.AddChild(useTagCheck);
        modeRow.AddChild(useKillCheck);
        outer.AddChild(modeRow);

        // ── Row 1a: prototype ID + live validation (visible in proto/kill mode)
        var searchRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 2) };

        var protoLabel = new Label { Text = "Proto: ", VerticalAlignment = VAlignment.Center };
        var protoIcon = new EntityPrototypeView
        {
            MinWidth = 24, MinHeight = 24,
            Margin = new Thickness(0, 0, 4, 0),
            VerticalAlignment = VAlignment.Center,
            Visible = false,
        };
        var protoField = new LineEdit { PlaceHolder = "Prototype ID (e.g. SheetSteel)", HorizontalExpand = true, MinWidth = 180 };
        var statusLabel = new Label
        {
            Text = string.Empty,
            Margin = new Thickness(6, 0),
            VerticalAlignment = VAlignment.Center,
            FontColorOverride = Color.FromHex("#888888"),
        };

        searchRow.AddChild(protoLabel);
        searchRow.AddChild(protoIcon);
        searchRow.AddChild(protoField);
        searchRow.AddChild(statusLabel);
        outer.AddChild(searchRow);

        // ── Row 1b: tag ID input (hidden in proto mode)
        var tagRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 0, 0, 2), Visible = false };
        var tagField = new LineEdit { PlaceHolder = "Tag ID (e.g. Trash)", HorizontalExpand = true, MinWidth = 180 };
        var tagStatusLabel = new Label
        {
            Text = string.Empty,
            Margin = new Thickness(6, 0),
            VerticalAlignment = VAlignment.Center,
            FontColorOverride = Color.FromHex("#888888"),
        };
        tagRow.AddChild(new Label { Text = "Tag:  ", VerticalAlignment = VAlignment.Center });
        tagRow.AddChild(tagField);
        tagRow.AddChild(tagStatusLabel);
        outer.AddChild(tagRow);

        void UpdateModeVisibility()
        {
            searchRow.Visible = !useTagCheck.Pressed;
            tagRow.Visible = useTagCheck.Pressed;
            protoLabel.Text = useKillCheck.Pressed ? "Kill:  " : "Proto: ";
            protoField.PlaceHolder = useKillCheck.Pressed ? "Mob prototype ID (e.g. NFMobCarp)" : "Prototype ID (e.g. SheetSteel)";
        }

        useTagCheck.OnToggled += args =>
        {
            if (args.Pressed)
                useKillCheck.Pressed = false;
            UpdateModeVisibility();
        };

        useKillCheck.OnToggled += args =>
        {
            if (args.Pressed)
                useTagCheck.Pressed = false;
            UpdateModeVisibility();
        };

        // Row 2: display name + amount + add button
        var addRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal };

        var nameField = new LineEdit { PlaceHolder = "Display name (auto-filled)", MinWidth = 150 };
        var amountField = new LineEdit { PlaceHolder = "20", MinWidth = 100 };
        var addBtn = new Button { Text = "Add Requirement", MinWidth = 110 };

        addRow.AddChild(new Label { Text = "Name: ", VerticalAlignment = VAlignment.Center });
        addRow.AddChild(nameField);
        addRow.AddChild(new Label { Text = " Qty: ", Margin = new Thickness(6, 0), VerticalAlignment = VAlignment.Center });
        addRow.AddChild(amountField);
        addRow.AddChild(addBtn);
        outer.AddChild(addRow);

        // Live prototype validation: on each keystroke look up the proto
        protoField.OnTextChanged += args =>
        {
            var id = args.Text.Trim();
            if (string.IsNullOrWhiteSpace(id))
            {
                protoIcon.Visible = false;
                statusLabel.Text = string.Empty;
                return;
            }

            if (_protoManager.TryIndex<EntityPrototype>(id, out var proto))
            {
                protoIcon.SetPrototype(id);
                protoIcon.Visible = true;

                // If this prototype has a stack, note it — any stack variant will be accepted in-game.
                var hasStack = proto.TryGetComponent<StackComponent>(out var stackComp);
                var stackNote = hasStack ? $" [{stackComp!.StackTypeId} stacks accepted]" : string.Empty;
                statusLabel.Text = $"✓ {proto.Name}{stackNote}";
                statusLabel.FontColorOverride = Color.FromHex("#aaffaa");

                // Auto-fill display name if it hasn't been manually set
                if (string.IsNullOrWhiteSpace(nameField.Text))
                    nameField.Text = proto.Name;
            }
            else
            {
                protoIcon.Visible = false;
                statusLabel.Text = "✗ Not found";
                statusLabel.FontColorOverride = Color.FromHex("#ff8888");
            }
        };

        tagField.OnTextChanged += args =>
        {
            var id = args.Text.Trim();
            if (string.IsNullOrWhiteSpace(id))
            {
                tagStatusLabel.Text = string.Empty;
                return;
            }

            if (_protoManager.HasIndex<TagPrototype>(id))
            {
                tagStatusLabel.Text = "✓ Valid tag";
                tagStatusLabel.FontColorOverride = Color.FromHex("#aaffaa");
                if (string.IsNullOrWhiteSpace(nameField.Text))
                    nameField.Text = id;
            }
            else
            {
                tagStatusLabel.Text = "✗ Tag not found";
                tagStatusLabel.FontColorOverride = Color.FromHex("#ff8888");
            }
        };

        addBtn.OnPressed += _ =>
        {
            if (!long.TryParse(amountField.Text.Trim(), out var amount) || amount <= 0)
                return;

            var displayName = string.IsNullOrWhiteSpace(nameField.Text) ? null : nameField.Text.Trim();

            if (useTagCheck.Pressed)
            {
                var tagId = tagField.Text.Trim();
                if (string.IsNullOrWhiteSpace(tagId))
                    return;
                if (!_protoManager.HasIndex<TagPrototype>(tagId))
                    return;

                OnAddRequirement?.Invoke(goalId, null, tagId, false, displayName, amount);

                tagField.Text = string.Empty;
            }
            else
            {
                var protoId = protoField.Text.Trim();
                if (string.IsNullOrWhiteSpace(protoId))
                    return;
                if (!_protoManager.HasIndex<EntityPrototype>(protoId))
                    return;

                OnAddRequirement?.Invoke(goalId, protoId, null, useKillCheck.Pressed, displayName, amount);

                protoField.Text = string.Empty;
                protoIcon.Visible = false;
                statusLabel.Text = string.Empty;
            }

            nameField.Text = string.Empty;
            amountField.Text = string.Empty;
        };

        return outer;
    }

    private Control BuildEditForm(CommunityGoalData goal)
    {
        var form = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(20, 2) };

        form.AddChild(new Label { Text = "── Edit Goal ──", FontColorOverride = Color.FromHex("#ffdd88") });

        var titleRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2) };
        titleRow.AddChild(new Label { Text = "Title:", MinWidth = 60 });
        var titleEdit = new LineEdit { Text = goal.Title, HorizontalExpand = true };
        titleRow.AddChild(titleEdit);
        form.AddChild(titleRow);

        var descRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2) };
        descRow.AddChild(new Label { Text = "Desc:", MinWidth = 60 });
        var descEdit = new LineEdit { Text = goal.Description, HorizontalExpand = true };
        descRow.AddChild(descEdit);
        form.AddChild(descRow);

        var roundRow = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 2) };
        roundRow.AddChild(new Label { Text = "Start:", MinWidth = 45 });
        var startEdit = new LineEdit { Text = goal.StartRound?.ToString() ?? string.Empty, MinWidth = 80, PlaceHolder = "(any)" };
        roundRow.AddChild(startEdit);
        roundRow.AddChild(new Label { Text = " End:", Margin = new Thickness(8, 0, 4, 0) });
        var endEdit = new LineEdit { Text = goal.EndRound?.ToString() ?? string.Empty, MinWidth = 80, PlaceHolder = "(never)" };
        roundRow.AddChild(endEdit);
        form.AddChild(roundRow);

        var saveBtn = new Button { Text = "Save Changes", Margin = new Thickness(0, 4) };
        saveBtn.OnPressed += _ =>
        {
            var title = titleEdit.Text.Trim();
            var desc = descEdit.Text.Trim();
            if (string.IsNullOrWhiteSpace(title))
                return;

            int? startRound = int.TryParse(startEdit.Text.Trim(), out var s) ? s : null;
            int? endRound = int.TryParse(endEdit.Text.Trim(), out var e) ? e : null;

            OnUpdateGoal?.Invoke(goal.Id, title, desc, startRound, endRound, goal.IsActive);
        };
        form.AddChild(saveBtn);

        return form;
    }
}
