name: Wayfarer Feature Request
description: Suggest an idea for this project
labels: ["S: Untriaged"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out an issue. This template is intended for requesting a feature to be added.
        For feedback or help running Wayfarer 14, please join our [Discord](https://discord.gg/QpVfma2eAp).
  - type: input
    attributes:
      label: Guidelines
      description: |
        Have you read the [Spacestation 14 PR Guidelines](https://docs.spacestation14.io/en/getting-started/pr-guideline)?
        Does this PR you are attaching adhere to those guidelines?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Features
      description: Please describe what this request adds, and why you wish to have it included on the server
    validations:
      required: true
  - type: textarea
    attributes:
      label: Benefits
      description: What benefit would this request have for players of the server?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Estimates
      description: In your estimate, what would be needed to complete this request? Would it need changes to the engine in C#? Just changes to items with YML? Sprites or Sound Effects? Etc. Etc?
    validations:
      required: false
