using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Examine.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterDetailWindow : FancyWindow
{
    public CharacterDetailWindow()
    {
        RobustXamlLoader.Load(this);

        // Set tab titles
        TabContainer.SetTabTitle(0, Loc.GetString("character-window-tab-description"));
        TabContainer.SetTabTitle(1, Loc.GetString("character-window-tab-consent"));
        TabContainer.SetTabTitle(2, Loc.GetString("character-window-tab-commend"));
    }

    public void SetCharacterInfo(string characterName, string roleplayLevel)
    {
        Title = Loc.GetString("character-window-title");
        CharacterName.Text = characterName;
        RoleplayLevel.Text = roleplayLevel;
    }

    public void SetDescription(FormattedMessage description)
    {
        DescriptionText.SetMessage(description);
    }

    public void SetConsent(FormattedMessage consent)
    {
        ConsentText.SetMessage(consent);
    }
}
