using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Examine.UI;

[GenerateTypedNameReferences]
public sealed partial class CharacterDetailWindow : FancyWindow
{
    private Label _characterName = default!;
    private Label _jobTitle = default!;
    private TabContainer _tabContainer = default!;
    private RichTextLabel _descriptionText = default!;
    private RichTextLabel _consentText = default!;

    public CharacterDetailWindow()
    {
        RobustXamlLoader.Load(this);

        _characterName = FindControl<Label>("CharacterName");
        _jobTitle = FindControl<Label>("JobTitle");
        _tabContainer = FindControl<TabContainer>("TabContainer");
        _descriptionText = FindControl<RichTextLabel>("DescriptionText");
        _consentText = FindControl<RichTextLabel>("ConsentText");

        // Set tab titles
        _tabContainer.SetTabTitle(0, Loc.GetString("character-window-tab-description"));
        _tabContainer.SetTabTitle(1, Loc.GetString("character-window-tab-consent"));
    }

    public void SetCharacterInfo(string characterName, string jobTitle)
    {
        Title = Loc.GetString("character-window-title");
        _characterName.Text = characterName;
        _jobTitle.Text = jobTitle;
    }

    public void SetDescription(FormattedMessage description)
    {
        _descriptionText.SetMessage(description);
    }

    public void SetConsent(FormattedMessage consent)
    {
        _consentText.SetMessage(consent);
    }
}
