using Content.Shared._WF.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class OutlawObjectivesUiFragment : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public OutlawObjectivesUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(List<OutlawObjectiveEntry> entries)
    {
        ObjectiveList.RemoveAllChildren();

        foreach (var entry in entries)
        {
            var row = new OutlawObjectivesUiRow();
            row.SetEntry(entry, _prototype.Index(entry.Objective));

            ObjectiveList.AddChild(row);
        }
    }
}
