using Content.Client.Message;
using Content.Shared._NF.Bank;
using Content.Shared._WF.CartridgeLoader.Cartridges;
using Content.Shared._WF.OutlawObjectives;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._WF.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class OutlawObjectivesUiRow : PanelContainer
{
    public OutlawObjectivesUiRow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetEntry(OutlawObjectiveEntry entry, OutlawObjectivePrototype objective)
    {
        SsdMarker.Text = entry.IsSsd ? "Zzz" : string.Empty;

        var target = ("target", (object) FormattedMessage.EscapeText(entry.Target));

        Title.SetMarkup(Loc.GetString(objective.Title, target));
        Description.SetMarkup(Loc.GetString(objective.Description, target));
        Reward.SetMarkup(Loc.GetString("outlaw-objectives-reward",
            ("chits", objective.RewardDC),
            ("cash", BankSystemExtensions.ToIndependentString(objective.RewardSpesos))));
    }
}
