// Wayfarer: Character resume from cryosleep feature - UI window
using Content.Client._WF.CryoSleep;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CryoSleep;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class ResumeCharacterWindow : FancyWindow
{
    public event Action<NetEntity>? OnCharacterSelected;

    private readonly CryoSleepClientSystem _cryoSystem;

    public ResumeCharacterWindow()
    {
        RobustXamlLoader.Load(this);
        _cryoSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<CryoSleepClientSystem>();
        _cryoSystem.OnCharactersResponse += OnRefreshedCharacters;
    }

    private void OnRefreshedCharacters(GetStoredCharactersResponseMessage msg)
    {
        // Re-populate while the window is open (e.g. after a removal).
        PopulateCharacters(msg.Characters);

        // Close if nothing is left.
        if (msg.Characters.Count == 0)
            Close();
    }

    protected override void Dispose(bool disposing)
    {
        _cryoSystem.OnCharactersResponse -= OnRefreshedCharacters;
        base.Dispose(disposing);
    }

    public void PopulateCharacters(List<StoredCharacterInfo> characters)
    {
        CharacterListContainer.DisposeAllChildren();

        if (characters.Count == 0)
        {
            var noCharLabel = new Label
            {
                Text = Loc.GetString("resume-character-window-no-characters"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(10)
            };
            CharacterListContainer.AddChild(noCharLabel);
            return;
        }

        foreach (var character in characters)
        {
            // Outer row: info area + remove button side by side.
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                MinHeight = 80,
                Margin = new Thickness(0, 0, 0, 8)
            };

            // Left: resume button (takes up most of the width)
            var resumeButton = new Button
            {
                HorizontalExpand = true,
                MinHeight = 80,
                StyleIdentifier = "mainMenu"
            };

            var contentBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalExpand = true,
                Margin = new Thickness(12, 8)
            };

            contentBox.AddChild(new Label
            {
                Text = character.CharacterName,
                StyleClasses = { "LabelHeading" },
                Margin = new Thickness(0, 0, 0, 4)
            });
            contentBox.AddChild(new Label
            {
                Text = character.JobName,
                Margin = new Thickness(0, 0, 0, 2)
            });
            contentBox.AddChild(new Label
            {
                Text = "Cryo Location: " + character.StationName,
                StyleClasses = { "LabelSmall" },
                FontColorOverride = Color.DarkGray
            });

            resumeButton.AddChild(contentBox);
            resumeButton.OnPressed += _ =>
            {
                OnCharacterSelected?.Invoke(character.Body);
                Close();
            };

            // Right: remove button (fixed width, with inline confirm)
            var removeButton = new Button
            {
                Text = Loc.GetString("resume-character-window-remove-button"),
                MinWidth = 80,
                MinHeight = 80,
                Margin = new Thickness(4, 0, 0, 0),
                VerticalAlignment = VAlignment.Stretch
            };

            var body = character.Body; // capture for lambda

            var confirmed = false;
            removeButton.OnPressed += _ =>
            {
                if (!confirmed)
                {
                    confirmed = true;
                    removeButton.Text = Loc.GetString("resume-character-window-remove-confirm");
                    removeButton.ModulateSelfOverride = Color.OrangeRed;
                }
                else
                {
                    _cryoSystem.RequestRemoveCharacter(body);
                }
            };

            // Clicking elsewhere in the row resets the confirm state.
            resumeButton.OnPressed += _ => { confirmed = false; };

            row.AddChild(resumeButton);
            row.AddChild(removeButton);
            CharacterListContainer.AddChild(row);
        }
    }
}
