// Wayfarer: Character resume from cryosleep feature - UI window
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.CryoSleep;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class ResumeCharacterWindow : FancyWindow
{
    public event Action<NetEntity>? OnCharacterSelected;

    public ResumeCharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void PopulateCharacters(List<StoredCharacterInfo> characters)
    {
        CharacterListContainer.DisposeAllChildren();

        if (characters.Count == 0)
        {
            var noCharLabel = new Label
            {
                Text = Loc.GetString("resume-character-window-no-characters"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(10)
            };
            CharacterListContainer.AddChild(noCharLabel);
            return;
        }

        foreach (var character in characters)
        {
            var button = new Button
            {
                HorizontalExpand = true,
                MinHeight = 80,
                Margin = new Thickness(0, 0, 0, 8),
                StyleIdentifier = "mainMenu"
            };
            
            button.OnPressed += _ =>
            {
                OnCharacterSelected?.Invoke(character.Body);
                Close();
            };
            
            var contentBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                VerticalExpand = true,
                Margin = new Thickness(12, 8)
            };
            
            var nameLabel = new Label
            {
                Text = character.CharacterName,
                StyleClasses = { "LabelHeading" },
                Margin = new Thickness(0, 0, 0, 4)
            };
            
            var jobTitleLabel = new Label
            {
                Text = character.JobName,
                Margin = new Thickness(0, 0, 0, 2)
            };
            
            var stationLabel = new Label
            {
                Text = "Cryo Location: " + character.StationName,
                StyleClasses = { "LabelSmall" },
                FontColorOverride = Color.DarkGray
            };
            
            contentBox.AddChild(nameLabel);
            contentBox.AddChild(jobTitleLabel);
            contentBox.AddChild(stationLabel);
            button.AddChild(contentBox);
            CharacterListContainer.AddChild(button);
        }
    }
}
