- type: job
  id: NFPirateCaptain
  name: job-name-nf-pirate-captain
  description: job-description-nf-pirate-captain
  playTimeTracker: JobPirateCaptain
  whitelisted: true
  startingGear: WantedOutlawStartingGear
  requirements:
  - !type:DepartmentTimeRequirement
    department: Antag # Outlaw
    time: 28800 # 8 hours
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconWantedOutlaw"
  supervisors: job-supervisors-freebooters-union
  weight: 40
  displayWeight: 40
  setPreference: true
  newPlayerMessage: false
  access:
  - Pirate
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: AutoPirateCaptain
    - type: SpecialSectorStationRecord # must be given on spawn
      recordGeneration: Normal # Real DNA/fingerprint/job on the criminal record so CGP can match to the wanted entry.
    - type: WantedOutlaw # Wayfarer: triggers sector record + Wanted status + CGP radio ping at spawn
    - type: DisableSuitSensors
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: chameleonOutfit
  id: NFPirateCaptainChameleonOutfit
  job: NFPirateCaptain

- type: startingGear
  id: WantedOutlawStartingGear
  equipment:
    pocket1: BasePirateUplinkRadioPirateCaptain

- type: roleLoadout
  id: JobNFPirateCaptain
  groups:
  - WFJumpsuit
  - WFOuterClothing
  - WFBackpack
  - WFShoes
  - WFHead
  - NFPirateEars
  - WFGloves
  - WFWantedOutlawPDA
  - WFGlasses
  - WFFace
  - WFBelt
  - WFNeck
  - OutlawEncryptionKey
  - WFBoxSurvival
  - WFWallet
  - WFCartridge
  - WFImplanter
  - PirateBackpackItems
  - WFHandItems
  - NFSpeciesSpecific
  - WFSidearm
  - WFLongarm
  - WFAmmo
  canCustomizeName: true # pseudonym?
  canCustomizeCrimeReason: true
