using System.IO;
using System.Linq;
using System.Text;
using Content.Client.UserInterface.Controls;
using Content.Shared.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client._WF.Instruments.UI;

[GenerateTypedNameReferences]
public sealed partial class PlaylistMenu : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IFileDialogManager _dialogs = default!;

    public EntityUid Instrument { get; init; }

    // Argument is the selected track index, or 0 if none is selected.
    public Action<int>? OnPlay { get; init; }

    // Prevents stacking file dialogs if the user clicks Add, Save, or Load again while one is still open.
    private bool _dialogOpen;

    public PlaylistMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        AddButton.OnPressed += OnAddPressed;
        RenameButton.OnPressed += OnRenamePressed;
        RemoveButton.OnPressed += OnRemovePressed;
        ClearButton.OnPressed += OnClearPressed;
        PlayButton.OnPressed += OnPlayPressed;
        SaveButton.OnPressed += OnSavePressed;
        LoadButton.OnPressed += OnLoadPressed;

        _entManager.System<PlaylistSystem>().PlaylistChanged += OnPlaylistChanged;
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _entManager.System<PlaylistSystem>().PlaylistChanged -= OnPlaylistChanged;
        base.Dispose(disposing);
    }

    protected override void Opened()
    {
        base.Opened();
        Refresh();
    }

    private void OnPlaylistChanged(EntityUid uid)
    {
        if (uid == Instrument)
            Refresh();
    }

    private void Refresh()
    {
        var data = _entManager.System<PlaylistSystem>().GetPlaylist(Instrument);

        TrackList.Clear();
        for (var i = 0; i < data.Tracks.Count; i++)
        {
            var track = data.Tracks[i];
            var displayName = string.IsNullOrWhiteSpace(track.Name)
                ? Loc.GetString("instruments-playlist-menu-track-default", ("n", i + 1))
                : track.Name;
            TrackList.AddItem(data.Active && i == data.CurrentIndex
                ? Loc.GetString("instruments-playlist-menu-track-current", ("name", displayName))
                : displayName);
        }
    }

    // The file dialog is awaited, so the window may close before it returns.
    private async void OnAddPressed(ButtonEventArgs obj)
    {
        if (_dialogOpen)
            return;

        var filters = new FileDialogFilters(new FileDialogFilters.Group("mid", "midi"));
        _dialogOpen = true;
        await using var file = await _dialogs.OpenFile(filters);
        _dialogOpen = false;

        if (Disposed || file == null)
            return;

        var bytes = file.CopyToArray();
        var system = _entManager.System<PlaylistSystem>();
        var data = system.GetPlaylist(Instrument);
        data.Tracks.Add(new PlaylistTrack(bytes, string.Empty));
        system.NotifyChanged(Instrument);
    }

    private int GetSelectedIndex() =>
        TrackList.GetSelected().FirstOrDefault() is { } sel ? TrackList.IndexOf(sel) : -1;

    private void OnRenamePressed(ButtonEventArgs obj)
    {
        var index = GetSelectedIndex();
        if (index < 0)
            return;

        var system = _entManager.System<PlaylistSystem>();
        var data = system.GetPlaylist(Instrument);
        var current = data.Tracks[index].Name;
        var entry = new QuickDialogEntry(
            "name",
            QuickDialogEntryType.ShortText,
            Loc.GetString("instruments-playlist-menu-rename-prompt"),
            string.IsNullOrWhiteSpace(current) ? null : current);
        var dialog = new DialogWindow(
            Loc.GetString("instruments-playlist-menu-rename-title"),
            new List<QuickDialogEntry> { entry });
        // Captured index can be stale if tracks are removed while the dialog is open.
        dialog.OnConfirmed = results =>
        {
            if (index >= data.Tracks.Count)
                return;
            data.Tracks[index].Name = results["name"].Trim();
            system.NotifyChanged(Instrument);
        };
    }

    private void OnRemovePressed(ButtonEventArgs obj)
    {
        var index = GetSelectedIndex();
        if (index < 0)
            return;

        var system = _entManager.System<PlaylistSystem>();
        var data = system.GetPlaylist(Instrument);

        data.Tracks.RemoveAt(index);
        if (data.Tracks.Count == 0)
        {
            data.Active = false;
            data.CurrentIndex = 0;
        }
        else if (data.CurrentIndex >= data.Tracks.Count)
        {
            data.CurrentIndex = 0;
        }
        system.NotifyChanged(Instrument);
    }

    private void OnClearPressed(ButtonEventArgs obj)
    {
        var system = _entManager.System<PlaylistSystem>();
        var data = system.GetPlaylist(Instrument);
        data.Tracks.Clear();
        data.Active = false;
        data.CurrentIndex = 0;
        system.NotifyChanged(Instrument);
    }

    private void OnPlayPressed(ButtonEventArgs obj)
    {
        OnPlay?.Invoke(Math.Max(0, GetSelectedIndex()));
    }

    // SS14 sandbox blocks File, Path, FileStream, and BinaryWriter. Writes go to the
    // dialog's Stream directly; int32 length prefixes use BitConverter.GetBytes.
    // BinaryReader is allowed, so loads use it.
    private const int MaxTrackCount = 2048;
    private const int MaxNameBytes = 1024;
    private const int MaxMidiBytes = 4 * 1024 * 1024;

    private async void OnSavePressed(ButtonEventArgs obj)
    {
        if (_dialogOpen)
            return;

        var data = _entManager.System<PlaylistSystem>().GetPlaylist(Instrument);
        if (data.Tracks.Count == 0)
            return;

        var filters = new FileDialogFilters(new FileDialogFilters.Group("midplaylist"));
        _dialogOpen = true;
        var result = await _dialogs.SaveFile(filters);
        _dialogOpen = false;

        if (Disposed || result == null)
            return;

        await using var stream = result.Value.fileStream;
        stream.Write(Encoding.UTF8.GetBytes("WPLY"), 0, 4);
        WriteInt32(stream, 1);
        WriteInt32(stream, data.Tracks.Count);
        foreach (var track in data.Tracks)
        {
            WriteLengthPrefixedBytes(stream, Encoding.UTF8.GetBytes(track.Name));
            WriteLengthPrefixedBytes(stream, track.Bytes);
        }
    }

    private async void OnLoadPressed(ButtonEventArgs obj)
    {
        if (_dialogOpen)
            return;

        var filters = new FileDialogFilters(new FileDialogFilters.Group("midplaylist"));
        _dialogOpen = true;
        await using var file = await _dialogs.OpenFile(filters);
        _dialogOpen = false;

        if (Disposed || file == null)
            return;

        var loaded = new List<PlaylistTrack>();
        try
        {
            using var reader = new BinaryReader(file, Encoding.UTF8);
            if (Encoding.ASCII.GetString(reader.ReadBytes(4)) != "WPLY")
                return;

            var version = reader.ReadInt32();
            if (version != 1)
                return;

            var count = reader.ReadInt32();
            if (count < 0 || count > MaxTrackCount)
                return;

            for (var i = 0; i < count; i++)
            {
                var nameLen = reader.ReadInt32();
                if (nameLen < 0 || nameLen > MaxNameBytes)
                    return;
                var nameBytes = reader.ReadBytes(nameLen);
                if (nameBytes.Length != nameLen)
                    return;

                var midiLen = reader.ReadInt32();
                if (midiLen < 0 || midiLen > MaxMidiBytes)
                    return;
                var midiBytes = reader.ReadBytes(midiLen);
                if (midiBytes.Length != midiLen)
                    return;

                loaded.Add(new PlaylistTrack(midiBytes, Encoding.UTF8.GetString(nameBytes)));
            }
        }
        catch (IOException)
        {
            // Covers EndOfStreamException for truncated files. The load aborts; the existing playlist is untouched.
            return;
        }

        var system = _entManager.System<PlaylistSystem>();
        var data = system.GetPlaylist(Instrument);
        data.Tracks.Clear();
        data.Tracks.AddRange(loaded);
        data.Active = false;
        data.CurrentIndex = 0;
        system.NotifyChanged(Instrument);
    }

    private static void WriteInt32(Stream stream, int value)
    {
        var bytes = BitConverter.GetBytes(value);
        stream.Write(bytes, 0, 4);
    }

    private static void WriteLengthPrefixedBytes(Stream stream, byte[] data)
    {
        WriteInt32(stream, data.Length);
        stream.Write(data, 0, data.Length);
    }
}
