using Content.Client.UserInterface.Controls;
using Content.Shared._WF.Radio;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Radio.UI;

[UsedImplicitly]
public sealed class RadioReceiverBoundUserInterface : BoundUserInterface
{
    [ViewVariables]
    private RadioReceiverMenu? _menu;

    public RadioReceiverBoundUserInterface(EntityUid owner, Enum uiKey) : base(owner, uiKey) { }

    protected override void Open()
    {
        base.Open();
        _menu = new RadioReceiverMenu(Owner);
        _menu.OnChannelChanged += channel => SendMessage(new RadioReceiverSetChannelMessage(channel));
        _menu.OnPowerToggled += on => SendMessage(new RadioReceiverTogglePowerMessage(on));
        _menu.OnVolumeChanged += vol => SendMessage(new RadioReceiverSetVolumeMessage(vol));
        _menu.OnClose += Close;
        _menu.OpenCentered();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _menu?.Close();
    }

    protected override void UpdateState(BoundUserInterfaceState state)
    {
        base.UpdateState(state);
        if (state is RadioReceiverBoundUIState s)
            _menu?.Update(s);
    }
}

[GenerateTypedNameReferences]
public sealed partial class RadioReceiverMenu : FancyWindow
{
    public event Action<int>? OnChannelChanged;
    public event Action<bool>? OnPowerToggled;
    public event Action<float>? OnVolumeChanged;

    public RadioReceiverMenu(EntityUid owner)
    {
        RobustXamlLoader.Load(this);

        RadioIcon.SetEntity(owner);
        PowerButton.OnPressed += args => OnPowerToggled?.Invoke(args.Button.Pressed);
        VolumeSlider.OnValueChanged += OnVolumeSliderChanged;
        VolumeSlider.OnKeyBindUp += OnVolumeSliderReleased;
    }

    private void OnVolumeSliderChanged(Robust.Client.UserInterface.Controls.Range _)
    {
        var percent = (int) Math.Round(VolumeSlider.Value);
        VolumeValueLabel.Text = Loc.GetString("wf-radio-receiver-menu-volume-value", ("percent", percent));

        // Only send when the slider is released, not while it is being dragged.
        if (!VolumeSlider.Grabbed)
            SendVolume();
    }

    private void OnVolumeSliderReleased(GUIBoundKeyEventArgs args)
    {
        SendVolume();
    }

    private void SendVolume()
    {
        OnVolumeChanged?.Invoke((int) Math.Round(VolumeSlider.Value) / 100f);
    }

    public void Update(RadioReceiverBoundUIState state)
    {
        PowerButton.Pressed = state.PoweredOn;
        PowerButton.Text = Loc.GetString(state.PoweredOn
            ? "wf-radio-receiver-menu-power-on"
            : "wf-radio-receiver-menu-power-off");

        if (!VolumeSlider.Grabbed)
        {
            var percent = (int) Math.Round(Math.Clamp(state.Volume, 0f, 1f) * 100f);
            VolumeSlider.SetValueWithoutEvent(percent);
            VolumeValueLabel.Text = Loc.GetString("wf-radio-receiver-menu-volume-value", ("percent", percent));
        }

        TunedChannelLabel.Text = Loc.GetString("wf-radio-receiver-menu-tuned-channel", ("channel", state.Channel));
        string? tunedName = null;
        if (state.OnAir != null)
        {
            foreach (var entry in state.OnAir)
            {
                if (entry.Channel != state.Channel)
                    continue;
                tunedName = entry.Name;
                break;
            }
        }
        TunedConsoleLabel.Text = tunedName ?? Loc.GetString("wf-radio-receiver-menu-tuned-none");

        ConsoleList.RemoveAllChildren();

        var onAir = state.OnAir;
        if (onAir == null || onAir.Count == 0)
        {
            ConsoleList.AddChild(new Label
            {
                Text = Loc.GetString("wf-radio-receiver-menu-no-broadcasts"),
                HorizontalAlignment = HAlignment.Center,
            });
            return;
        }

        foreach (var entry in onAir)
        {
            var button = new Button
            {
                Text = Loc.GetString("wf-radio-receiver-menu-entry",
                    ("channel", entry.Channel),
                    ("name", entry.Name)),
                HorizontalExpand = true,
            };
            button.OnPressed += _ => OnChannelChanged?.Invoke(entry.Channel);
            ConsoleList.AddChild(button);
        }
    }
}
