using System.Collections.Generic;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared._WF.Radio;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WF.Radio.UI;

[UsedImplicitly]
public sealed class RadioBroadcastConsoleBoundUserInterface : BoundUserInterface
{
    [ViewVariables]
    private RadioBroadcastConsoleMenu? _menu;

    public RadioBroadcastConsoleBoundUserInterface(EntityUid owner, Enum uiKey) : base(owner, uiKey) { }

    protected override void Open()
    {
        base.Open();
        _menu = new RadioBroadcastConsoleMenu(Owner);
        _menu.OnChannelChanged += raw =>
        {
            if (int.TryParse(raw.Trim(), out var channel) && channel > 0)
                SendMessage(new RadioBroadcastConsoleSetChannelMessage(channel));
        };
        _menu.OnNameChanged += name => SendMessage(new RadioBroadcastConsoleSetNameMessage(name));
        _menu.OnBroadcastToggled += on => SendMessage(new RadioBroadcastConsoleToggleMessage(on));
        _menu.OnPresetsChanged += ids => SendMessage(new RadioBroadcastConsoleSetPresetsMessage(ids));
        _menu.OnClose += Close;
        _menu.OpenCentered();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
            _menu?.Close();
    }

    protected override void UpdateState(BoundUserInterfaceState state)
    {
        base.UpdateState(state);
        if (state is RadioBroadcastConsoleBoundUIState s)
            _menu?.Update(s);
    }
}

[GenerateTypedNameReferences]
public sealed partial class RadioBroadcastConsoleMenu : FancyWindow
{
    public event Action<string>? OnChannelChanged;
    public event Action<string>? OnNameChanged;
    public event Action<bool>? OnBroadcastToggled;
    public event Action<List<ProtoId<RadioPresetPrototype>>>? OnPresetsChanged;

    private readonly List<(string Id, CheckBox Box)> _presetCheckboxes = new();

    private bool _suppressEmit;

    public RadioBroadcastConsoleMenu(EntityUid owner)
    {
        RobustXamlLoader.Load(this);

        ConsoleIcon.SetEntity(owner);
        NameLineEdit.IsValid = s => s.Length <= RadioBroadcastConstants.MaxBroadcastNameLength;
        NameLineEdit.OnTextEntered += e => OnNameChanged?.Invoke(e.Text);
        NameLineEdit.OnFocusExit += e => OnNameChanged?.Invoke(e.Text);

        ChannelLineEdit.OnTextEntered += e => OnChannelChanged?.Invoke(e.Text);
        ChannelLineEdit.OnFocusExit += e => OnChannelChanged?.Invoke(e.Text);

        BroadcastButton.OnPressed += args => OnBroadcastToggled?.Invoke(args.Button.Pressed);
    }

    public void Update(RadioBroadcastConsoleBoundUIState state)
    {
        // Do not overwrite a field the player is typing in.
        if (!NameLineEdit.HasKeyboardFocus())
            NameLineEdit.Text = state.BroadcastName;
        if (!ChannelLineEdit.HasKeyboardFocus())
            ChannelLineEdit.Text = state.Channel.ToString();
        BroadcastButton.Pressed = state.Broadcasting;
        BroadcastButton.Text = Loc.GetString(state.Broadcasting
            ? "wf-radio-console-menu-broadcast-on"
            : "wf-radio-console-menu-broadcast-off");

        RebuildPresetCheckboxes(state);
    }

    private void RebuildPresetCheckboxes(RadioBroadcastConsoleBoundUIState state)
    {
        var pressed = new HashSet<string>(state.Presets);

        // Keep the same rows when nothing changed, or the scroll bar jumps back to the top.
        if (PresetSetMatches(state.AvailablePresets))
        {
            _suppressEmit = true;
            try
            {
                foreach (var (id, box) in _presetCheckboxes)
                    box.Pressed = pressed.Contains(id);
            }
            finally
            {
                _suppressEmit = false;
            }
            return;
        }

        PresetList.RemoveAllChildren();
        _presetCheckboxes.Clear();

        _suppressEmit = true;
        try
        {
            foreach (var entry in state.AvailablePresets)
            {
                var box = new CheckBox
                {
                    Text = entry.Name,
                    Pressed = pressed.Contains(entry.Id),
                };
                box.Label.StyleClasses.Add(StyleNano.StyleClassLabelKeyText);
                box.OnToggled += _ =>
                {
                    if (_suppressEmit)
                        return;
                    EmitSelection();
                };
                PresetList.AddChild(box);
                _presetCheckboxes.Add((entry.Id, box));
            }
        }
        finally
        {
            _suppressEmit = false;
        }
    }

    private bool PresetSetMatches(List<RadioPresetEntry> available)
    {
        if (_presetCheckboxes.Count != available.Count)
            return false;
        for (var i = 0; i < available.Count; i++)
        {
            if (_presetCheckboxes[i].Id != available[i].Id)
                return false;
        }
        return true;
    }

    private void EmitSelection()
    {
        var selected = new List<ProtoId<RadioPresetPrototype>>();
        foreach (var (id, box) in _presetCheckboxes)
        {
            if (box.Pressed)
                selected.Add(id);
        }
        OnPresetsChanged?.Invoke(selected);
    }
}
