using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Bank;
using Content.Shared._WF.Corporations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.Corporations;

[GenerateTypedNameReferences]
public sealed partial class CorporationAtmMenu : FancyWindow
{
    public event Action? DepositRequest;
    public event Action<int>? WithdrawRequest;

    public CorporationAtmMenu()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("corp-atm-title");
        DepositButton.OnPressed += _ => DepositRequest?.Invoke();
        WithdrawButton.OnPressed += _ =>
        {
            if (int.TryParse(AmountEdit.Text, out var amount) && amount > 0)
                WithdrawRequest?.Invoke(amount);
        };
    }

    public void UpdateState(CorporationAtmUiState state)
    {
        var hasCorp = state.CorporationName != null;

        CorpNameLabel.Text = hasCorp
            ? state.CorporationName!
            : Loc.GetString("corp-atm-no-corp");

        CorpBalanceLabel.Text = BankSystemExtensions.ToSpesoString(state.Balance);

        if (state.Deposit < 0)
            CashInsertedLabel.Text = Loc.GetString("corp-atm-wrong-cash-short");
        else
            CashInsertedLabel.Text = BankSystemExtensions.ToSpesoString(state.Deposit);

        StatusLabel.Text = string.IsNullOrEmpty(state.StatusMessage)
            ? string.Empty
            : Loc.GetString(state.StatusMessage);

        DepositButton.Disabled = !hasCorp || state.Deposit <= 0;
        WithdrawButton.Disabled = !hasCorp || !state.CanWithdraw;
    }
}
