using Content.Client.UserInterface.Controls;
using Content.Shared._WF.RoleplayLeveling.Events;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WF.RoleplayLeveling.UI;

[GenerateTypedNameReferences]
public sealed partial class MyCommendsWindow : FancyWindow
{
    public MyCommendsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Populate(List<CommendEntryData> commends, int totalCommends)
    {
        TotalCommendsLabel.Text = totalCommends == 1
            ? "Total commends received: 1"
            : $"Total commends received: {totalCommends}";

        CommendList.RemoveAllChildren();

        if (commends.Count == 0)
        {
            var empty = new Label
            {
                Text = "No commends yet.",
                FontColorOverride = Color.Gray,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 20),
            };
            CommendList.AddChild(empty);
            return;
        }

        foreach (var entry in commends)
        {
            CommendList.AddChild(BuildEntry(entry));
        }
    }

    private static Control BuildEntry(CommendEntryData entry)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
        };
        var styleBox = new StyleBoxFlat
        {
            BackgroundColor = new Color(0.12f, 0.12f, 0.13f),
        };
        styleBox.SetContentMarginOverride(StyleBox.Margin.All, 8);
        panel.PanelOverride = styleBox;

        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            HorizontalExpand = true,
        };
        panel.AddChild(vbox);

        // Header: giver name + date
        var header = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, HorizontalExpand = true };
        var giverLabel = new Label
        {
            Text = entry.IsPrivate ? "Anonymous" : entry.GiverName,
            FontColorOverride = new Color(0.8f, 0.8f, 1.0f),
            HorizontalExpand = true,
        };
        var dateLabel = new Label
        {
            Text = entry.ReceivedAt.ToLocalTime().ToString("MMM d, yyyy"),
            FontColorOverride = Color.Gray,
        };
        header.AddChild(giverLabel);
        header.AddChild(dateLabel);
        vbox.AddChild(header);

        // Comment text — use RichTextLabel so it word-wraps
        if (!string.IsNullOrWhiteSpace(entry.Comment))
        {
            var comment = new RichTextLabel
            {
                HorizontalExpand = true,
            };
            comment.SetMessage(entry.Comment);
            vbox.AddChild(comment);
        }

        return panel;
    }
}
