using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Enums;
using Content.Client.Stylesheets; // Wayfarer
using Robust.Shared.Timing; // Wayfarer

namespace Content.Client.StationRecords;

[GenerateTypedNameReferences]
public sealed partial class GeneralRecord : Control
{
    [Dependency] private readonly IGameTiming _gameTiming = default!; // Wayfarer

    public Action<uint>? OnDeletePressed;
    public Action<uint>? OnRemoveCrewPressed; // Wayfarer

    // Wayfarer: Remove button asks "Are you sure?" on first click, removes on second click within 3 seconds
    private uint? _removeRecordId;
    private TimeSpan? _removeButtonResetOn;

    public GeneralRecord(GeneralStationRecord record, bool canDelete, uint? id, bool canRegisterCrew) // Wayfarer: canRegisterCrew
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // Wayfarer
        RecordName.Text = record.Name;
        Age.Text = Loc.GetString("general-station-record-console-record-age", ("age", record.Age.ToString()));
        Title.Text = Loc.GetString("general-station-record-console-record-title",
            ("job", Loc.GetString(record.JobTitle)));
        Species.Text = Loc.GetString("general-station-record-console-record-species", ("species", record.Species));
        Gender.Text = Loc.GetString("general-station-record-console-record-gender",
            ("gender", record.Gender.ToString()));
        Fingerprint.Text = Loc.GetString("general-station-record-console-record-fingerprint",
            ("fingerprint", record.Fingerprint ?? Loc.GetString("generic-not-available-shorthand")));
        Dna.Text = Loc.GetString("general-station-record-console-record-dna",
            ("dna", record.DNA ?? Loc.GetString("generic-not-available-shorthand")));

        if (canDelete && id != null )
        {
            DeleteButton.Visible = true;
            DeleteButton.OnPressed += _ => OnDeletePressed?.Invoke(id.Value);
        }

        // Wayfarer: Remove button
        if (canRegisterCrew && id is { } recordId)
        {
            _removeRecordId = recordId;
            RemoveCrewButton.Visible = true;
            RemoveCrewButton.OnPressed += _ => OnRemoveCrewButtonPressed();
        }
        // End Wayfarer
    }

    // Wayfarer: Remove button
    private void OnRemoveCrewButtonPressed()
    {
        if (_removeButtonResetOn is null)
        {
            _removeButtonResetOn = _gameTiming.CurTime.Add(TimeSpan.FromSeconds(3));
            RemoveCrewButton.AddStyleClass(StyleBase.ButtonCaution);
            RemoveCrewButton.Text = Loc.GetString("register-crew-confirm");
            return;
        }

        ResetRemoveButton();
        if (_removeRecordId is { } id)
            OnRemoveCrewPressed?.Invoke(id);
    }

    private void ResetRemoveButton()
    {
        _removeButtonResetOn = null;
        RemoveCrewButton.RemoveStyleClass(StyleBase.ButtonCaution);
        RemoveCrewButton.Text = Loc.GetString("register-crew-remove");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_removeButtonResetOn != null && _gameTiming.CurTime > _removeButtonResetOn)
            ResetRemoveButton();
    }
    // End Wayfarer
}
