- type: job
  id: Bailiff
  name: job-name-bailiff
  description: job-description-bailiff
  playTimeTracker: JobWarden
  whitelisted: true
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 259200 # 72 hours
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 86400 # 24 hours
  startingGear: BailiffGear
  icon: JobIconBailiff
  supervisors: job-supervisors-sheriff
  weight: 150
  displayWeight: 60
  canBeAntag: false
  access:
  - Armory
  - Sergeant
  - Bailiff
  - Brigmedic
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, NFSDTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: BailiffGear
  equipment:
    pocket1: NFWeaponPistolUniversalNfsdLessLethal
    pocket2: HoloprojectorNfsd
  storage:
    back:
    - Flash
    - NFMagazineHighCapacityPistol35Overpressure
    - NFMagazineHighCapacityPistol35Rubber
    - BaseSecurityUplinkRadioOfficer
    - FrontierUplinkCoin5
    - ShipVoucherNfsdBailiff
    - RubberStampBailiff

- type: chameleonOutfit
  id: BailiffChameleonOutfit
  job: Bailiff
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterCoatNfsdFormal
    neck: ClothingNeckNfsdBadgeWarden
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdCream
    shoes: ClothingShoesBootsNfsdCreamFilled
