- type: job
  id: Cadet
  name: job-name-cadet-nf
  description: job-description-cadet-nf
  playTimeTracker: JobSecurityCadet
  whitelisted: true
  startingGear: CadetGear
  icon: JobIconCadetNF
  supervisors: job-supervisors-cadet
  weight: 70
  displayWeight: 10
  canBeAntag: false
  accessGroups:
  - CadetNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, NFSDTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: CadetGear
  equipment:
#    pocket1: NFWeaponPistolUniversalNfsdLessLethal # Wayfarer: Sidearms selectable in loadout
    pocket2: BookSecurity
  storage:
    back:
    - Flash
#    - NFMagazineHighCapacityPistol35
#    - NFMagazineHighCapacityPistol35Rubber # Wayfarer
#    - FrontierUplinkCoin10 # Wayfarer: Unusable by Cadet

- type: chameleonOutfit
  id: CadetChameleonOutfit
  job: Cadet
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterArmorNfsd
    neck: ClothingNeckNfsdBadgeSecurityCadet
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdBrown
    shoes: ClothingShoesBootsNfsdBrownFilled

