- type: job
  id: Deputy
  name: job-name-deputy
  description: job-description-deputy
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityCadet
      time: 21600 # 6 hours as Cadet
  startingGear: DeputyGear
  icon: JobIconDeputy
  supervisors: job-supervisors-sergeant
  weight: 130
  displayWeight: 40
  canBeAntag: false
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, NFSDTrackingImplant ]
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: DeputyGear
  equipment:
    pocket1: BaseSecurityUplinkRadioOfficer # Wayfarer: NFWeaponPistolUniversalNfsdLessLethal<BaseSecurityUplinkRadioOfficer
  storage:
    back:
    - Flash
#    - NFMagazineHighCapacityPistol35Overpressure
#    - NFMagazineHighCapacityPistol35Rubber # Wayfarer
#    - BaseSecurityUplinkRadioOfficer # Wayfarer: Moved to Pocket

- type: chameleonOutfit
  id: DeputyChameleonOutfit
  job: Deputy
  hasMindShield: true
  equipment:
    head: ClothingHeadHatNfsdBeretBrown
    mask: ClothingMaskGasNfsd
    eyes: ClothingEyesGlassesNfsd
    outerClothing: ClothingOuterArmorNfsd
    neck: ClothingNeckNfsdBadgeSecurity
    belt: ClothingBeltNfsdFilled
    gloves: ClothingHandsGlovesCombatNfsdBrown
    shoes: ClothingShoesBootsNfsdBrownFilled
