using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._WF.CCVar;
using Content.Shared._WF.Administration.PrayerLog;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.IoC;
using Robust.Shared.Network;

namespace Content.Client._WF.Administration.UI.PrayerLog;

[GenerateTypedNameReferences]
public sealed partial class PrayerLogWindow : DefaultWindow
{
    private const int TimeRatio = 2;
    private const int PlayerRatio = 3;
    private const int ItemRatio = 3;
    private const int TypeRatio = 2;
    private const int ContentRatio = 6;
    private const int FollowColWidth = 80;

    private BoxContainer _entriesContainer = default!;
    private Label _headerContent = default!;

    private readonly IConfigurationManager _cfg;

    public event Action<NetUserId>? OnFollowRequested;

    private IEnumerable<PrayerLogEntryRow> Rows => _entriesContainer.Children.OfType<PrayerLogEntryRow>();

    private float ContentWidth => Math.Max(Width * 0.32f, 150f);

    public PrayerLogWindow()
    {
        RobustXamlLoader.Load(this);
        _cfg = IoCManager.Resolve<IConfigurationManager>();
        BuildScrollBody();

        SearchBox.OnTextChanged += _ => UpdateFilter();
        OnResized += RefreshContentWidth;

        AlertCheckBox.Pressed = _cfg.GetCVar(WFCVars.AdminPrayerAlert);
        AlertCheckBox.OnToggled += args =>
            _cfg.SetCVar(WFCVars.AdminPrayerAlert, args.Pressed);
    }

    private void BuildScrollBody()
    {
        ScrollBody.AddChild(BuildHeaderRow());
        ScrollBody.AddChild(new PanelContainer
        {
            StyleClasses = { "LowDivider" },
            Margin = new Thickness(0, 0, 0, 2),
        });

        _entriesContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
        };
        ScrollBody.AddChild(_entriesContainer);
    }

    private BoxContainer BuildHeaderRow()
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 4,
            Margin = new Thickness(0, 0, 0, 2),
        };

        _headerContent = Cell(Loc.GetString("prayer-log-column-content"), ContentRatio, heading: true);
        PinContentWidth(_headerContent, ContentWidth);
        AddColumns(row,
            new Control { MinWidth = FollowColWidth, MaxWidth = FollowColWidth },
            Cell(Loc.GetString("prayer-log-column-time"), TimeRatio, heading: true),
            Cell(Loc.GetString("prayer-log-column-player"), PlayerRatio, heading: true),
            Cell(Loc.GetString("prayer-log-column-item"), ItemRatio, heading: true),
            Cell(Loc.GetString("prayer-log-column-type"), TypeRatio, heading: true),
            _headerContent);
        return row;
    }

    // Adds each cell to the row with a vertical separator between them.
    private static void AddColumns(BoxContainer row, params Control[] cells)
    {
        for (var i = 0; i < cells.Length; i++)
        {
            if (i > 0)
                row.AddChild(new VSeparator());
            row.AddChild(cells[i]);
        }
    }

    private static Label Cell(string text, int ratio, bool heading = false)
    {
        var label = new Label
        {
            Text = text,
            HorizontalExpand = true,
            SizeFlagsStretchRatio = ratio,
            Align = Label.AlignMode.Left,
            VerticalAlignment = VAlignment.Top,
            ClipText = true,
        };
        if (heading)
            label.StyleClasses.Add("LabelHeading");
        return label;
    }

    // Pins a cell to a fixed width so it neither expands nor grows with its content.
    private static void PinContentWidth(Control cell, float width)
    {
        cell.HorizontalExpand = false;
        cell.MinWidth = width;
        cell.MaxWidth = width;
    }

    public void Populate(List<PrayerLogEntry> entries)
    {
        _entriesContainer.RemoveAllChildren();

        foreach (var entry in entries)
        {
            var row = new PrayerLogEntryRow(entry, ContentWidth);
            row.OnFollow += uid => OnFollowRequested?.Invoke(uid);
            _entriesContainer.AddChild(row);
        }

        RefreshContentWidth();
        EmptyLabel.Visible = entries.Count == 0;
        UpdateFilter();
    }

    private void RefreshContentWidth()
    {
        var width = ContentWidth;
        PinContentWidth(_headerContent, width);
        foreach (var row in Rows)
            row.SetContentWidth(width);
    }

    private void UpdateFilter()
    {
        var search = SearchBox.Text;
        var shown = 0;
        var total = 0;

        foreach (var row in Rows)
        {
            total++;
            row.Visible = row.Matches(search);
            if (row.Visible)
                shown++;
        }

        CountLabel.Text = Loc.GetString("prayer-log-count",
            ("shown", shown), ("total", total));
    }

    public sealed class PrayerLogEntryRow : BoxContainer
    {
        public PrayerLogEntry Entry { get; }
        public event Action<NetUserId>? OnFollow;

        private readonly RichTextLabel _content;

        public PrayerLogEntryRow(PrayerLogEntry entry, float contentWidth)
        {
            Entry = entry;
            Orientation = BoxContainer.LayoutOrientation.Horizontal;
            SeparationOverride = 4;

            var follow = new Button
            {
                Text = Loc.GetString("prayer-log-follow"),
                ToolTip = Loc.GetString("prayer-log-follow-tooltip"),
                MinWidth = FollowColWidth,
                MaxWidth = FollowColWidth,
                VerticalAlignment = VAlignment.Top,
            };
            follow.OnPressed += _ => OnFollow?.Invoke(Entry.UserId);

            _content = new RichTextLabel { VerticalAlignment = VAlignment.Top };
            PinContentWidth(_content, contentWidth);
            _content.SetMessage(entry.Content);

            AddColumns(this,
                follow,
                Cell(entry.RoundTime.ToString(@"hh\:mm\:ss"), TimeRatio),
                Cell(FormatPlayer(entry), PlayerRatio),
                Cell(entry.ItemName, ItemRatio),
                Cell(entry.Type, TypeRatio),
                _content);
        }

        public void SetContentWidth(float width) => PinContentWidth(_content, width);

        public bool Matches(string search) =>
            string.IsNullOrEmpty(search)
            || new[] { Entry.PlayerName, Entry.CharacterName, Entry.ItemName, Entry.Type, Entry.Content }
                .Any(s => s.Contains(search, StringComparison.OrdinalIgnoreCase));

        private static string FormatPlayer(PrayerLogEntry e) =>
            string.IsNullOrEmpty(e.CharacterName)
                ? e.PlayerName
                : $"{e.PlayerName} ({e.CharacterName})";
    }
}
