name: "Labels Remover"
on:
  pull_request_target:
    types: [closed]
jobs:
  remove_label:
    if: github.event.pull_request.merged == true
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: |
          S: Needs Review
          S: Untriaged
