name: "PR: Auto-assign"

on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    if: github.repository == 'project-wayfarer/wayfarer-14'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: "PR: Auto-assign"
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request

            await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                assignees: [pr.user.login]
            })

            await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                team_reviewers: [process.env.REVIEWERS_TEAM_SLUG ?? 'reviewers']
            });
